#!/bin/bash -e

# Usage: /sbin/slapd-restore dbnum file [gunzipFile]
dbnum=$1
file=$2

backupPath="/data/backup"
file="$backupPath/$file"

TEMP_FILE=$(/usr/bin/mktemp)
gunzip -c $file > $TEMP_FILE

# stop slapd
sv stop /container/run/process/slapd

/sbin/setuser openldap slapadd -F /etc/ldap/slapd.d -n $dbnum -l $TEMP_FILE

# restart slapd
sv start /container/run/process/slapd

rm $TEMP_FILE
